# Generated by Django 6.0.1 on 2026-02-17 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('image', models.URLField()),
                ('category', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diseases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DurstData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.TextField()),
                ('ursachen_text', models.TextField()),
                ('red_flags', models.TextField()),
                ('diagnostic_gold_standard', models.TextField()),
                ('guideline_link', models.URLField()),
                ('disease', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='durst_data', to='pathology_app.disease')),
            ],
        ),
        migrations.CreateModel(
            name='ImmediateAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('durst_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immediate_actions', to='pathology_app.durstdata')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='pathology_app.disease')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_title', models.CharField(max_length=200)),
                ('question_options', models.JSONField()),
                ('correct_index', models.IntegerField()),
                ('explanation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='pathology_app.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='RiskFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('durst_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_factors', to='pathology_app.durstdata')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='pathology_app.disease')),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('durst_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptoms', to='pathology_app.durstdata')),
            ],
        ),
        migrations.CreateModel(
            name='UrsacheKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('durst_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ursache_keywords', to='pathology_app.durstdata')),
            ],
        ),
    ]
