# Generated by Django 6.0.1 on 2026-02-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathology_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
