# Generated by Django 6.0.1 on 2026-02-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathology_app', '0002_alter_disease_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='image',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
