# Generated by Django 6.0.1 on 2026-02-20 22:32

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathology_app', '0003_alter_disease_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disease',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='durstdata',
            options={'ordering': ['disease'], 'verbose_name': 'Durst Data', 'verbose_name_plural': 'Durst Data'},
        ),
        migrations.AlterModelOptions(
            name='immediateaction',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='riskfactor',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['source_name']},
        ),
        migrations.AlterModelOptions(
            name='symptom',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='ursachekeyword',
            options={'ordering': ['keyword']},
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_options',
            new_name='options',
        ),
        migrations.RemoveField(
            model_name='durstdata',
            name='ursachen_text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_title',
        ),
        migrations.AddField(
            model_name='durstdata',
            name='ursachen',
            field=models.TextField(default=0, verbose_name='Ursachen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='disease',
            name='category',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='disease',
            name='disease_id',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='durstdata',
            name='diagnostic_gold_standard',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='durstdata',
            name='guideline_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='durstdata',
            name='red_flags',
            field=models.TextField(blank=True, help_text='Warnsignale, die eine Lungenembolie nahelegen können'),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ursachekeyword',
            name='keyword',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='source',
            unique_together={('disease', 'link')},
        ),
        migrations.AlterUniqueTogether(
            name='ursachekeyword',
            unique_together={('durst_data', 'keyword')},
        ),
        migrations.AddIndex(
            model_name='disease',
            index=models.Index(fields=['category'], name='pathology_a_categor_d27839_idx'),
        ),
    ]
