# Generated by Django 6.0.1 on 2026-07-31 22:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathology_app', '0004_alter_disease_options_alter_durstdata_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='disease_id',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='disease',
            unique_together={('owner', 'disease_id')},
        ),
    ]
